"""Lock the real qwen3-asr media transcript fixture as version-controlled evidence."""

import unittest
from pathlib import Path

FIXTURE = Path(__file__).parent / "golden" / "formats" / "media" / "transcript_zh_90s.txt"


class MediaAsrFixtureTests(unittest.TestCase):
    def test_real_qwen3_asr_zh_transcript_fixture_is_version_controlled(self) -> None:
        """Lock the real qwen3-asr 90s zh transcript as version-controlled evidence.

        The fixture was generated by running Qwen3-ASR-1.7B (cuda:0/bfloat16) on a
        90-second Chinese audio sample (YouTube video 3DlXq9nsQOE, public) via the
        project ``transcribe_media`` wrapper.
        It is an evidence snapshot, not a deterministic re-run target: ASR output can
        vary across model versions, so this test asserts the fixture exists and is a
        reasonable Chinese transcript rather than re-running ASR.
        """
        self.assertTrue(FIXTURE.exists(), f"media ASR fixture missing: {FIXTURE}")
        text = FIXTURE.read_text(encoding="utf-8").strip()
        self.assertGreater(len(text), 200)
        self.assertLess(len(text), 5000)
        self.assertRegex(text, r"[一-鿿]")


if __name__ == "__main__":
    unittest.main()
