import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from kbprep_worker.canonical_transcripts import parse_transcript_cues, read_transcript_cues


class CanonicalTranscriptTests(unittest.TestCase):
    def test_reads_gbk_srt_without_losing_timing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "lesson.srt"
            source.write_bytes(
                "\n".join([
                    "1",
                    "00:00:01,000 --> 00:00:03,000",
                    "主持人: 欢迎开始",
                ]).encode("gbk")
            )

            cues = read_transcript_cues(source)

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "1")
        self.assertEqual(cues[0].start_time, "00:00:01,000")
        self.assertEqual(cues[0].end_time, "00:00:03,000")
        self.assertEqual(cues[0].text, "主持人: 欢迎开始")

    def test_preserves_webvtt_cue_settings(self) -> None:
        cues = parse_transcript_cues(
            "\n".join([
                "WEBVTT",
                "",
                "intro",
                "00:00:01.000 --> 00:00:03.000 align:start position:0%",
                "Host: Welcome",
            ])
        )

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "intro")
        self.assertEqual(cues[0].settings, "align:start position:0%")

    def test_omits_webvtt_cue_settings_when_absent(self) -> None:
        cues = parse_transcript_cues(
            "\n".join([
                "WEBVTT",
                "",
                "intro",
                "00:00:01.000 --> 00:00:03.000",
                "Host: Welcome",
            ])
        )

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "intro")
        self.assertEqual(cues[0].settings, "")

    def test_reads_bom_webvtt_without_using_header_as_cue_identifier(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "lesson.vtt"
            source.write_bytes(
                "\ufeffWEBVTT\n00:00:01.000 --> 00:00:03.000\nHost: Welcome\n".encode("utf-8")
            )

            cues = read_transcript_cues(source)

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "1")

    def test_does_not_use_webvtt_header_as_cue_identifier(self) -> None:
        cues = parse_transcript_cues(
            "\n".join([
                "WEBVTT",
                "00:00:01.000 --> 00:00:03.000",
                "Host: Welcome",
            ])
        )

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "1")

    def test_does_not_use_webvtt_directive_as_cue_identifier(self) -> None:
        cues = parse_transcript_cues(
            "\n".join([
                "NOTE generated by tool",
                "00:00:01.000 --> 00:00:03.000",
                "Host: Welcome",
            ])
        )

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "1")

    def test_does_not_use_webvtt_style_or_region_as_cue_identifier(self) -> None:
        directives = (
            "NOTE",
            "STYLE",
            "REGION",
            "WEBVTT Kind: captions",
            "WEBVTT\tKind: captions",
            "NOTE generated",
            "NOTE\tgenerated",
            "STYLE css",
            "STYLE\tcss",
            "REGION id:subtitle",
            "REGION\tid:subtitle",
        )
        for directive in directives:
            with self.subTest(directive=directive):
                cues = parse_transcript_cues(
                    "\n".join([
                        directive,
                        "00:00:01.000 --> 00:00:03.000",
                        "Host: Welcome",
                    ])
                )

                self.assertEqual(len(cues), 1)
                self.assertEqual(cues[0].cue_id, "1")

    def test_does_not_use_dialogue_text_as_cue_identifier(self) -> None:
        cues = parse_transcript_cues(
            "\n".join([
                "Host: Welcome to the lesson.",
                "00:00:01.000 --> 00:00:03.000",
                "Guest: Hi",
            ])
        )

        self.assertEqual(len(cues), 1)
        self.assertEqual(cues[0].cue_id, "1")
        self.assertEqual(cues[0].text, "Guest: Hi")

    def test_missing_transcript_file_returns_empty_cues(self) -> None:
        cues = read_transcript_cues(Path("missing-transcript-file.srt"))

        self.assertEqual(cues, [])

    def test_read_bytes_os_error_returns_empty_cues(self) -> None:
        with patch.object(Path, "read_bytes", side_effect=OSError("cannot read")):
            cues = read_transcript_cues(Path("lesson.srt"))

        self.assertEqual(cues, [])

    def test_unreadable_transcript_encoding_returns_empty_cues(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "lesson.srt"
            source.write_bytes(b"\xff\xfe\x00\x00")

            cues = read_transcript_cues(source)

        self.assertEqual(cues, [])


if __name__ == "__main__":
    unittest.main()
