"""Lock the real qwen3-asr media transcript fixture as version-controlled evidence."""

import hashlib
import unittest
from pathlib import Path

FIXTURE = Path(__file__).parent / "golden" / "formats" / "media" / "transcript_zh_90s.txt"
FIXTURE_SHA256 = "62f8bb0e17b7cd9257ba69018855933a06a782e1fc2bb6abe42cafcbd46b5aaa"


class MediaAsrFixtureTests(unittest.TestCase):
    def test_real_qwen3_asr_zh_transcript_fixture_is_version_controlled(self) -> None:
        """Lock the real qwen3-asr 90s zh transcript as version-controlled evidence.

        The fixture was generated by running Qwen3-ASR-1.7B (cuda:0/bfloat16) on a
        90-second Chinese audio sample (YouTube video 3DlXq9nsQOE, public) via the
        project ``transcribe_media`` wrapper. It is an evidence snapshot: ASR output
        can vary across model versions, so CI does not re-run ASR. Instead the
        content hash below locks the current snapshot; any silent drift fails this
        test until the fixture is regenerated deliberately and the hash updated.
        """
        self.assertTrue(FIXTURE.exists(), f"media ASR fixture missing: {FIXTURE}")
        text = FIXTURE.read_text(encoding="utf-8").strip()
        self.assertGreater(len(text), 200)
        self.assertLess(len(text), 5000)
        self.assertRegex(text, r"[一-鿿]")

    def test_real_qwen3_asr_zh_transcript_fixture_hash_is_locked(self) -> None:
        """Content-hash lock that catches silent fixture drift in CI."""
        self.assertTrue(FIXTURE.exists(), f"media ASR fixture missing: {FIXTURE}")
        actual = hashlib.sha256(FIXTURE.read_bytes()).hexdigest()
        self.assertEqual(
            actual,
            FIXTURE_SHA256,
            "media ASR fixture content drifted from the locked snapshot; regenerate "
            "it deliberately and update FIXTURE_SHA256",
        )


if __name__ == "__main__":
    unittest.main()
